name: GitHub Actions Demo
run-name: 🛠️ Running tests for ${{ github.actor }}'s PR.
on:
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize, edited, reopened ]
jobs:
  tests:
    name: Run Go tests
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3341:3341
        env:
          MYSQL_ROOT_HOST: "%"
          MYSQL_ROOT_PASSWORD: "secret"
          MYSQL_TCP_PORT: "3341"
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v2

      - name: Install go
        uses: actions/setup-go@v4
        with: { go-version: 1.21 }

      - name: Build dependencies
        run: |
          sh ./scripts/build-di.sh

      - name: Run go mod tidy
        run: |
          go mod tidy   

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56.2
          skip-go-installation: true
          skip-pkg-cache: true

      - name: Run golangci-lint
        run: |
          golangci-lint run ./...

      - name: Run go vet
        run: |
          go vet ./...
          
      - name: Run go test
        run: |
          go test ./...
